//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguaterosApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedido
    {
        public int DetalleId { get; set; }
        public string Cantidad { get; set; }
        public decimal Precio { get; set; }
        public int Pedido_PedidoId { get; set; }
        public int Producto_ProductoId { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
