//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AguaterosApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio
    {
        public int PrecioId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public decimal Valor { get; set; }
        public int Producto_ProductoId { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
